/home/jovyan/.venv/torch1.10.0-py3.8-cuda11.3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py:688: UserWarning: Detected KeyboardInterrupt, attempting graceful shutdown...
  rank_zero_warn("Detected KeyboardInterrupt, attempting graceful shutdown...")
Traceback (most recent call last):
  File "train.py", line 49, in <module>
    main()
  File "train.py", line 46, in main
    trainer.test(model, DataLoader(test_set), batch_size = batch_size)
TypeError: test() got an unexpected keyword argument 'batch_size'